*   Multimídia - Matrizes e Vetores (Exercício 1)

*   Felipe Daniel Dias dos Santos - 11711ECP004

*   Graduação em Engenharia de Computação - Faculdade de Engenharia Elétrica - Universidade Federal de Uberlândia

In [ ]:
#a)
A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]

#Elemento da linha 0 e coluna 1 da matriz A 
AI = (A[0][1])
print(AI)

4


In [ ]:
#b)
import numpy as np

#Construção de matriz 3x4 formada por inteiros aleatórios
x2 = np.random.randint(10, size=(3, 4))
print(x2)

[[6 9 5 8]
 [3 9 1 7]
 [0 3 0 6]]


In [ ]:
#Todos os elementos da coluna 0 da matriz x2
print(x2[:, 0])

[6 3 0]


In [ ]:
#Todos os elementos da linha 0 da matriz x2
print(x2[0, :])

[6 9 5 8]


In [ ]:
#Todos os elementos da linha 0 até a linha 2 e da coluna 2 até a coluna 3 da matriz x2
print(x2[0:2, 2:3])

[[5]
 [1]]


In [ ]:
#Fazer todos os elementos da coluna 0 iguais a zero
A4 = x2
A4[:, 0] = 0
print(A4)

[[0 9 5 8]
 [0 9 1 7]
 [0 3 0 6]]


In [ ]:
#O elemento da última linha e última coluna da matriz x2
A5 = x2[-1, -1]
print(A5)

6


In [ ]:
#Todos os elementos da última coluna da matriz x2
A6 = x2[:, -1]
print(A6)

[8 7 6]


In [ ]:
#O elemento da última linha e primeira coluna antes da última da matriz x2
A7 = x2[-1, -2]
print(A7)

0


In [ ]:
#Matriz transposta de x2
A8 = np.transpose(x2)
print(A8)

[[0 0 0]
 [9 9 3]
 [5 1 0]
 [8 7 6]]


In [ ]:
#c)

#I) Vetor com todos os valores de 1 a 20
v1 = np.arange(1, 21)
print(v1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
#II) Vetor com todos os valores pares de 1 a 20
v2 = np.arange(2, 21, 2)
print(v2)

[ 2  4  6  8 10 12 14 16 18 20]


In [ ]:
#III) Vetor com todos os valores ímpares de 1 a 20
v3 = np.arange(1, 20, 2)
print(v3)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
#IV) Vetores com valores de 0 a 1, intervalados de 0.1
v4 = np.arange(0, 1.1, 0.1)
print(v4)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


No item 'c', foi utilizada a função "arange" para a construção dos vetores. A função "arange" constroi arrays com elementos dentro de um dado intervalo semi aberto, espaçados por um valor. Essa função possui a seguinte sintaxe: "arange(start, end, step)", onde:

"start" é o número inicial do intervalo (incluso no intervalo);

"end" é o número final do intervalo (não incluso no intervalo, portanto, para incluí-lo, deve fazer "end = final + 1");

"step" é o intervalo entre os números gerados.