*   Multimídia - Matrizes e Vetores (Exercício 3)

*   Felipe Daniel Dias dos Santos - 11711ECP004

*   Graduação em Engenharia de Computação - Faculdade de Engenharia Elétrica - Universidade Federal de Uberlândia

In [ ]:
import numpy as np

x2 = np.random.randint(10, size=(3, 4))

#a) Soma de todos os elementos da matriz x2
M1 = np.sum(x2)
print(M1)

58


In [ ]:
#b) Vetor mostrando os valores máximos de cada coluna da matriz x2
M2 = x2.max(axis = 0)
print(M2)

[6 9 6 8]


In [ ]:
#c) Valor máximo da matriz x2
M3 = np.max(x2)
print(M3)

9


In [ ]:
#d) Vetor mostrando os valores mínimos de cada coluna da matriz x2
M4 = x2.min(axis = 0)
print(M4)

[3 1 1 2]


In [ ]:
#e) Valor mínimo da matriz x2
M5 = np.min(x2)
print(M5)

1


In [ ]:
#f)
E = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
print(E)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#I) Criar a matriz F como uma cópia de E, sem a última linha e coluna
F = E[0:3, 0:3]
print(F)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [ ]:
#II) Somar “+1” em todos os elementos pares da matriz E
G = (E % 2 == 0)
E[G] = E[G] + 1
print(E)

[[ 1  3  3  5]
 [ 5  7  7  9]
 [ 9 11 11 13]
 [13 15 15 17]]


In [ ]:
#III) Remova a primeira coluna de E
E = E[:, 1:]
print(E)

[[ 3  3  5]
 [ 7  7  9]
 [11 11 13]
 [15 15 17]]


Os itens I e III foram feitos utilizando o operador ':' para retirar colunas e linhas. O item II foi feito explorando o operador '%' para recuperar os itens pares da matriz 'E' e somar 1 a eles.