*   Multimídia - Matrizes e Vetores (Exercício 5)

*   Felipe Daniel Dias dos Santos - 11711ECP004

*   Graduação em Engenharia de Computação - Faculdade de Engenharia Elétrica - Universidade Federal de Uberlândia

In [ ]:
import numpy as np
from random import randint
from random import random
from random import seed

#a) Matriz de zeros de ordem 4
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#b) Matriz de uns de ordem 4
print(np.ones((4,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#c) Matriz de booleanos "True" de ordem 4
print(np.full((4,4), True))

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
#d) Gera um número pseudoaleatório entre 0 e 1, distribuído uniformemente
print(random())

0.20437902187321355


In [ ]:
#e) Matriz de números pseudoaleatórios de ordem 4, distribuídos normalmente
print(np.random.randn(4,4))

[[-0.79868394 -1.13869456  0.86712281 -1.75983886]
 [-1.72400344 -0.43325201 -0.70899279 -0.60096336]
 [-0.46647149  0.31110198 -1.32664623  1.74600541]
 [ 0.51065518  0.39276588  0.41144717  0.86559   ]]


In [ ]:
#f)

#I) 

#Cria um vetor de dimensão 5, com todos os elementos igual a zero, de tipo inteiro
Z1 = np.zeros((5, ), dtype = int)
print(Z1)

[0 0 0 0 0]


In [ ]:
#II) 

#Cria um vetor de dimensão 5, com todos os elementos igual a um, de tipo float
Z2 = np.ones(5)
print(Z2)

[1. 1. 1. 1. 1.]


In [ ]:
#III) 

#Gera um número pseudoaleatório inteiro, entre 2 e 5 (incluindo 2 e 5)
value = randint(2, 5)
print(value)

2


In [ ]:
#IV) Altera a semente do gerador de números pseudoaleatórios para 1. Dessa forma, se a semente sempre for a mesma, o gerador irá selecionar sempre o mesmo número
#Para que o gerador selecione números diferentes, é necessário alterar o valor da semente
#Assim, o comando "print(random())" irá mostrar sempre o mesmo número, como observado no item "V"

seed(1)

In [ ]:
#V) Gera um número pseudoaleatório uniformemente distribuído 
#Devido ao fato de a semente estar em 1 pelo comando "seed(1)" do item "IV", esse número gerado será o mesmo

print(random())

0.13436424411240122


In [ ]:
#VI) Gera um vetor de dimensão 5 de números pseudoaleatórios normalmente distribuídos

np.random.randn(5)

array([-0.16869577, -1.22194794,  0.98457598,  1.33150931,  1.16140849])